[package]
org = "tharindu"
name = "bike_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.6.0"

[ballerina.observe]
metricsEnabled = false
tracingEnabled = false
logsEnabled = true
logLevel = "DEBUG"
logFilePath = "./logs/bike-service.log"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.6.0"


