[package]
org = "tharindu"
name = "bike_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true
cloud="docker"

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"

[ballerina.observe]
metricsEnabled = false
tracingEnabled = false
logsEnabled = true
logLevel = "DEBUG"
logFilePath = "./logs/bike-service.log"
