version: '3.8'

services:
  bike_service_db:
    image: postgres:15
    container_name: bike_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bikes_db
      POSTGRES_USER: bike_service_user
      POSTGRES_PASSWORD: 1KiHEb8LC0VmvUe
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  bike-service:
    image: bike_service:latest
    depends_on:
      - bike_service_db
    ports:
      - '8090:8090'
    volumes:
      - ./Config.toml:/app/Config.toml
    environment:
      BAL_CONFIG_FILES: /app/Config.toml

volumes:
  pgdata:
