name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Ballerina
      - name: Set up Ballerina
      - uses: ballerina-platform/setup-ballerina@v1
        name: Install Ballerina
        with:
          version: 2201.3.2
      - run: bal version

      # Step 3: Build Ballerina service (produces Docker image)
      - name: Build bike_service
        run: bal build

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 5: Tag and push bike_service image
      - name: Tag and push Docker image
        run: |
          # Replace <local_image_name> with the Ballerina-generated image name
          docker tag ballerina/bike_service:latest thetharz/orbyte_bike_service:latest
          docker push thetharz/orbyte_bike_service:latest
